name: Publish2Confluence
on: 
  workflow_dispatch:
  push:
      branches: ['main', 'development']
      paths-ignore:
          - '**/README.md'
          - '.github/**'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown_to_confluence_job:
    runs-on: ubuntu-latest
    name: Converting Markdown to Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Sync Docs as Code - Confluence
        uses: Bhacaz/docs-as-code-confluence@v2
        with:
          folder: docs
          username: henrique.gurgacz@eneva.com.br
          password: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-base-url: https://eneva.atlassian.net/wiki
          space-key: '~712020ac12504fda354922b745409d45453f4f'
          parent-page-id: 201818188